### PR TITLE
tooltip added to display browser's timezone in ping details

### PR DESCRIPTION
**Pull request by NKETIAH53**

### CODE REVIEW

**Comment by NKETIAH53** [comment]
feature for issue # 1040

**Comment by cuu508** [comment]
Can you please describe the thinking behind this PR?

Looking at the code changes, IIUC, the tooltip would show the timestamp, formatted using browser's timezone, over each time cell. It would be the same date that's already displayed in the "Browser's time zone" cell. Why also display it in the tooltip?

**Comment by NKETIAH53** [comment]
With respect to the earlier conversation regarding what was expected, @mickBoat00 suggested displaying the time in full on hover. 
I only based the PR on your response to his comment, considering it may be the first step in a series of approaches you would prefer to be undertaken

**Comment by cuu508** [comment]
> I only based the PR on your response to his comment, considering it may be the first step in a series of approaches you would prefer to be undertaken

Did you by any chance use an LLM for this?

**Comment by NKETIAH53** [comment]
No, I did not.

**Comment by cuu508** [comment]
The "Ping Details" dialog is already fine – it displays the timestamp in browser's timezone in the "Browser's time zone" cell. There is no benefit to show it also in a tooltip.

Issue #1040 is about displaying a timestamp (instead of a relative value) *in the checks list*, "Last Ping" column.

**Pull request closed without merging**
