### PR TITLE
adds a unique parameter to the check creation API

### PR DESCRIPTION
**Pull request by foozmeat**
It only checks for name uniqueness.

for #82

### CODE REVIEW

**Comment by cuu508** [comment]
Hi @foozmeat , looks like useful feature, thanks for doing this!
Maybe instead of `unique=True` go with `unique=["name"]`. It's sort-of self-documenting, and a bit more future proof.
Also would be good to mention 200/201 status codes in the docs.

**Comment by foozmeat** [comment]
so `unique` would specify which field you want to be unique in the request?

I can update the docs with the result codes.

**Comment by cuu508** [comment]
Yes! Down the road we might want to support e.g. "require unique combination of name and tags" and express it as `unique=["name", "tags"]`.

**Comment by foozmeat** [comment]
I just went ahead and implemented unique checks for name, tags, timeout, and grace.

**Pull request merged**
