### PR TITLE
add custom configuration: CUSTOM_VIEW_DOWNTIMES_COUNT

### PR DESCRIPTION
**Pull request by muharihar**
Add custom configuration for check.downtimes, so we can view downtimes count by configuration CUSTOM_VIEW_DOWNTIMES_COUNT value (default: 3)

### CODE REVIEW

**Comment by cuu508** [comment]
Thanks for the PR. If this was merged, what value would you set it to? i.e., how many months of downtime statistics would you like to see?

**Comment by muharihar** [comment]
> Thanks for the PR. If this was merged, what value would you set it to? i.e., how many months of downtime statistics would you like to see?

we cat set it depend on the requirement, for example: 3, 6, 12 months (etc)

**Comment by cuu508** [comment]
What is your current requirement, and how is it decided?

If you want to see 6 or 12 months, it sounds like you are interested in seeing reliability trends over a longer time period. I think this would be better done from a separate report that can be run on demand:

* Crunching the downtime stats takes some work, and has to be done each time the details page is displayed. Showing 6 or 12 months would increase the work 2x and 4x.
* The additional downtime stats will also take space on screen, and push the "Schedule", "Notification Methods" and "Danger Zone" sections further down, making them harder to see and use.

**Comment by muharihar** [comment]
> What is your current requirement, and how is it decided?
> 
> If you want to see 6 or 12 months, it sounds like you are interested in seeing reliability trends over a longer time period. I think this would be better done from a separate report that can be run on demand:
> 
> * Crunching the downtime stats takes some work, and has to be done each time the details page is displayed. Showing 6 or 12 months would increase the amount of work 2x and 4x respectively.
> * The additional downtime stats will also take space on screen, and push the "Schedule", "Notification Methods" and "Danger Zone" sections further down, making them harder to see and use.

Your are absolutely right about it, thats why the default value is 3.

Our requirement is we need to display more than 3 month, (depend on the requirement:  if management decided to see more than 3 month, we can change it by set the CUSTOM_VIEW_DOWNTIMES_COUNT value)

Thank you

**Comment by cuu508** [comment]
Has management expressed a wish to see more than 3 months?

**Comment by muharihar** [comment]
> Has management expressed a wish to see more than 3 months?

Yup, they want to see more than 3 months

**Comment by cuu508** [comment]
I don't think this change fits the project well. Healthchecks focuses on real-time notifications when something does not happen on time, and not on long term statistics and analytics. I understand that from your perspective this looks like a trivial change that solves a concrete problem, but my perspective there's the cost of added complexity (even if small), of having another configuration parameter that needs to be documented and maintained, of additional tests, of integrating the change in `manage.py pruneflips` (and documenting and testing that) and perhaps of other stuff that I have not thought of.

**Comment by muharihar** [comment]
> I don't think this change fits the project well. Healthchecks focuses on real-time notifications when something does not happen on time, and not on long term statistics and analytics. I understand that from your perspective this looks like a trivial change that solves a concrete problem, but my perspective there's the cost of added complexity (even if small), of having another configuration parameter that needs to be documented and maintained, of additional tests, of integrating the change in `manage.py pruneflips` (and documenting and testing that) and perhaps of other stuff that I have not thought of.

ok, thanks you

**Pull request closed without merging**
