### PR TITLE
LineNotify Integration with Healthcheck 

### PR DESCRIPTION
**Pull request by carson0321**
Hi, I have integrated [LineNotify](https://notify-bot.line.me/en/) with it. [LineNotify](https://notify-bot.line.me/en/) is a notification service in [LINE](https://en.wikipedia.org/wiki/Line_(software)). The most common text messaging service used in Japan and Taiwan is by far [LINE](https://en.wikipedia.org/wiki/Line_(software)). Let's discuss this. Btw, there's a lack of iconfont. I would be appreciate if anyone could help to generate it.

Thanks.

### CODE REVIEW

**Comment by cuu508** [comment]
Hello @carson0321 – thanks for the PR! 
I gave the integration a quick test locally and all seemed to make sense, and worked – I got a test notification delivered to my phone. A couple questions:

* HTML markup in the notification message doesn't get rendered – I see "<b>DOWN</b>" markup on phone. I tried replacing HTML in the template with \*bold\* but that didn't work either. I'm very new to this service – perhaps you know how to get text formatting to work?
* I see notify-bot.line.me supports OAuth authentication, and developers can register their OAuth services. Implementing this would be a bit more work, but the end user experience might be nicer – what are your thoughts on that?

**Comment by carson0321** [comment]
@cuu508 Thank you for pointing out these questions. I noticed the HTML markup didn't get rendered in the notification message. LINE chat doesn't support HTML text rendering. Although we can place an asterisk on both sides of the text to display bold messages, it shows only on desktop. I'll remove the HTML markup to fix it.

With regard to the second question, you're right. LINE notify uses OAuth2 as the authorization mechanism. It can guide users to the its authorization page, receive the authorization code redirect, and exchange an access token with authorization code. Finally, notifications is sent by the access token. I'll implement it if I'm free. If you don't mind, you could merge this PR.

**Comment by cuu508** [comment]
@carson0321 just rebased and merged!

I'm all for better end user experience so would like to look at implementing OAuth2 auth flow for this integration. If you plan to look at it, that would be awesome. Otherwise, please let me know and I will give it a go myself.

**Comment by cuu508** [comment]
@carson0321 do you plan to implement the OAuth2 flow? If not, please let me know and I will take a crack at it!

**Comment by carson0321** [comment]
@cuu508  Yes, please give me some time so that I will do it. I have a lot on my plate recently.

**Comment by carson0321** [comment]
@cuu508 Hi, I see you've done https://github.com/healthchecks/healthchecks/commit/4f53325730142ca09f1c761108799e1bed1fb419 . So, please disregard the previous comment 😂. Thanks.

**Pull request closed without merging**
