### PR TITLE
Allow variables to be overwritten by local_settings.py

### PR DESCRIPTION
**Pull request by erickeller**
fixes the PING_ENDPOINT to be overwritten by local_settings

### CODE REVIEW

**Comment by cuu508** [comment]
I recommend setting `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` explicitly in local_settings.py.

If `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` are set in settings.py after importing local_settings.py then it's not possible to use custom ones any more. For example, in https://healthchecks.io, the ping endpoint is "https://hc-ping.com" not "https://healthchecks.io/ping/". And the email domain is also "hc-ping.com" not "healthchecks.io". In local_settings.py I have:

    SITE_ROOT = "https://healthchecks.io"
    PING_ENDPOINT = "https://hc-ping.com/"
    PING_EMAIL_DOMAIN = "hc-ping.com"

**Comment by cuu508** [comment]
I recommend setting `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` explicitly in local_settings.py.

If `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` are set in settings.py after importing local_settings.py then it's not possible to use custom ones any more. For example, in https://healthchecks.io, the ping endpoint is "https://hc-ping.com" not "https://healthchecks.io/ping/". And the email domain is also "hc-ping.com" not "healthchecks.io". In local_settings.py I have:

    SITE_ROOT = "https://healthchecks.io"
    PING_ENDPOINT = "https://hc-ping.com/"
    PING_EMAIL_DOMAIN = "hc-ping.com"

**Comment by cuu508** [comment]
I recommend setting `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` explicitly in local_settings.py.

If `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` are set in settings.py after importing local_settings.py then it's not possible to use custom ones any more. For example, in https://healthchecks.io, the ping endpoint is "https://hc-ping.com" not "https://healthchecks.io/ping/". And the email domain is also "hc-ping.com" not "healthchecks.io". In local_settings.py I have:

    SITE_ROOT = "https://healthchecks.io"
    PING_ENDPOINT = "https://hc-ping.com/"
    PING_EMAIL_DOMAIN = "hc-ping.com"

**Comment by cuu508** [comment]
I recommend setting `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` explicitly in local_settings.py.

If `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` are set in settings.py after importing local_settings.py then it's not possible to use custom ones any more. For example, in https://healthchecks.io, the ping endpoint is "https://hc-ping.com" not "https://healthchecks.io/ping/". And the email domain is also "hc-ping.com" not "healthchecks.io". In local_settings.py I have:

    SITE_ROOT = "https://healthchecks.io"
    PING_ENDPOINT = "https://hc-ping.com/"
    PING_EMAIL_DOMAIN = "hc-ping.com"

**Comment by cuu508** [comment]
I recommend setting `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` explicitly in local_settings.py.

If `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` are set in settings.py after importing local_settings.py then it's not possible to use custom ones any more. For example, in https://healthchecks.io, the ping endpoint is "https://hc-ping.com" not "https://healthchecks.io/ping/". And the email domain is also "hc-ping.com" not "healthchecks.io". In local_settings.py I have:

    SITE_ROOT = "https://healthchecks.io"
    PING_ENDPOINT = "https://hc-ping.com/"
    PING_EMAIL_DOMAIN = "hc-ping.com"

**Comment by cuu508** [comment]
I recommend setting `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` explicitly in local_settings.py.

If `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` are set in settings.py after importing local_settings.py then it's not possible to use custom ones any more. For example, in https://healthchecks.io, the ping endpoint is "https://hc-ping.com" not "https://healthchecks.io/ping/". And the email domain is also "hc-ping.com" not "healthchecks.io". In local_settings.py I have:

    SITE_ROOT = "https://healthchecks.io"
    PING_ENDPOINT = "https://hc-ping.com/"
    PING_EMAIL_DOMAIN = "hc-ping.com"

**Comment by cuu508** [comment]
I recommend setting `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` explicitly in local_settings.py.

If `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` are set in settings.py after importing local_settings.py then it's not possible to use custom ones any more. For example, in https://healthchecks.io, the ping endpoint is "https://hc-ping.com" not "https://healthchecks.io/ping/". And the email domain is also "hc-ping.com" not "healthchecks.io". In local_settings.py I have:

    SITE_ROOT = "https://healthchecks.io"
    PING_ENDPOINT = "https://hc-ping.com/"
    PING_EMAIL_DOMAIN = "hc-ping.com"

**Comment by cuu508** [comment]
I recommend setting `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` explicitly in local_settings.py.

If `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` are set in settings.py after importing local_settings.py then it's not possible to use custom ones any more. For example, in https://healthchecks.io, the ping endpoint is "https://hc-ping.com" not "https://healthchecks.io/ping/". And the email domain is also "hc-ping.com" not "healthchecks.io". In local_settings.py I have:

    SITE_ROOT = "https://healthchecks.io"
    PING_ENDPOINT = "https://hc-ping.com/"
    PING_EMAIL_DOMAIN = "hc-ping.com"

**Comment by cuu508** [comment]
I recommend setting `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` explicitly in local_settings.py.

If `PING_ENDPOINT` and `PING_EMAIL_DOMAIN` are set in settings.py after importing local_settings.py then it's not possible to use custom ones any more. For example, in https://healthchecks.io, the ping endpoint is "https://hc-ping.com" not "https://healthchecks.io/ping/". And the email domain is also "hc-ping.com" not "healthchecks.io". In local_settings.py I have:

    SITE_ROOT = "https://healthchecks.io"
    PING_ENDPOINT = "https://hc-ping.com/"
    PING_EMAIL_DOMAIN = "hc-ping.com"

**Comment by erickeller** [comment]
If set these in local_settings.py this will not being taken into account since the PING_ENDPOINT will always be localhost. Since its build up from HOST.

It's a bit misleading, but yes I can overwrite the PING_ENDPOINT in the local_settings.py

**Pull request closed without merging**
