### PR TITLE
Integration for Spike.sh

### PR DESCRIPTION
**Pull request by noob-master147**

### CODE REVIEW

**Comment by noob-master147** [comment]
screencapture-127-0-0-1-8000-projects-02c09574-6358-4a7a-92d7-7ca9d171d578-integrations-2020-07-08-11_39_44

screencapture-127-0-0-1-8000-projects-02c09574-6358-4a7a-92d7-7ca9d171d578-add-spike-2020-07-08-11_31_50

**Comment by cuu508** [comment]
Thanks for the PR, I'll check it out!

A couple notes so far:

* you've reformatted `templates/front/channels.html`  and `templates/front/welcome.html` so diffs are hard to read, and there will likely be merge conflicts for any private forks. Could you update these files with the new bits, but without reformatting?
* In `templates/front/channels.html` page, "Add More" section, all except the first three integrations are in alphabetic order. Spike should fit in between "SMS" and "Telegram".

**Comment by noob-master147** [comment]
Thanks @cuu508 for pointing these changes, I'll look into these issues.

**Comment by noob-master147** [comment]
Hey @cuu508 
I've made the relevant changes. 😄
Let me know if we require any other changes. 😄

**Comment by ktkaushik** [comment]
Thanks @noob-master147 for sending this PR 😊

**Comment by cuu508** [comment]
I made a bit of a mess with merging this – I wanted to rebase and squash the commits into one, but did it wrong initially. 
I think it should be all correct now.

**Comment by noob-master147** [comment]
hey @cuu508 
the issue you mentioned earlier has been resolved from our end, thanks for letting us know.

**Comment by cuu508** [comment]
@noob-master147 do you mean the issue about incidents not getting resolved when a check goes up? Just tested it again, and saw the previous behavior: sending an "up" notification creates a new incident. 

image

**Comment by noob-master147** [comment]
> @noob-master147 do you mean the issue about incidents not getting resolved when a check goes up? Just tested it again, and saw the previous behavior: sending an "up" notification creates a new incident.
> 
> image

@ktkaushik

**Pull request merged**
