### PR TITLE
Add body to Telegram notifications

### PR DESCRIPTION
**Pull request by f-f**
As per title, inspired by #735

### CODE REVIEW

**Comment by f-f** [comment]
Hi @cuu508, I noticed that #785 (a very similar change) was merged but this one was not, is there anything I could do to help move it forward?

**Comment by cuu508** [comment]
Hi @f-f, thanks for the PR! The next step is for me to test the changes. I hope to get around to it this week.

**Comment by f-f** [comment]
Sounds great, thanks!

**Comment by cuu508** [comment]
Just reviewed and tested the PR. Here are the things I'd like fixed or changed:

* Fix tests – some of the new test cases currently don't pass
* The telegram_message.html template does not output the ping body. The template uses the `{% line %}....{% endline %}` tags for precise whitespace control, and the body is not enclosed in these tags. (see the next point for an example on how to fix)
* The Telegram integration uses the "html" parsing mode, so Markdown syntax will not work:

image

use `<pre>` tags instead like so:


```
{% if body %}
{% line %}<pre>{{ body }}</pre>{% endline %}
{% endif %}
```

Result:

image

* The other integrations truncate long body at 1000 characters. For the sake of consistency, I'd like the Telegram integration to do the same.
* I think the pre section needs a label ("Last Ping Body"), otherwise, for some users, it may not be clear what the preformatted content is.

**Comment by f-f** [comment]
Thanks for the review @cuu508! I pushed a commit that should address all the feedback.

**Pull request merged**
