### PR TITLE
Spike Integration with Healthcheck

### PR DESCRIPTION
**Pull request by noob-master147**
@cuu508 , We have fixed Autoresolve functionality and test it. 
I am creating this PR again because the last PR got reverted.

### CODE REVIEW

**Comment by cuu508** [comment]
Closing, this was merged in 6300947c77f916879f54ee5036c5ec399532aa7f

**Comment by noob-master147** [comment]
Thanks @cuu508 
so i visited Healthcheck integration page and could not find Spike.sh integration there. Am i missing something here?
screencapture-healthchecks-io-projects-84fc3998-17dd-4302-8121-2ef8da4d14c8-integrations-2020-07-14-13_17_45

**Comment by cuu508** [comment]
I haven't deployed these changes yet – I'd like the issue in #393 be fixed first.

**Comment by ktkaushik** [comment]
Hey @cuu508, we did seem to have missed `UUID` that's generated for each check. We have fixed it and this is the expected flow - 

When a check goes `Down` 

1. If **NO** existing incident is found in either `triggered` or `acknowledged` state for the given `UUID`, then a new incident is created and alerts are sent
2. If an incident is found in `triggered` or `acknowledged` state then we append to events without sending any alert

When a check goes `Up`

1. If **NO** existing incident is found in either `triggered` or `acknowledged` state for the given `UUID`, then we ignore it instead of creating a new incident.
2. If an incident is found in `triggered` or `acknowledged` state then we **auto-resolve** the incident

Thanks for all the help and being so kind about it 😊

Also, thanks @noob-master147 for creating **Spike.sh** integration

**Comment by cuu508** [comment]
Great – precisely matches how I would expect it to work!

Just tested the integration again and it correctly triggered and resolved incidents. I went ahead and updated https://healthchecks.io – the Spike.sh integration is now available there.

**Comment by ktkaushik** [comment]
That is awesome. Did you know Healthchecks is our first 'native' integration? 🍻

**Comment by cuu508** [comment]
I did not – cheers to @noob-master147 and yourself for proposing and implementing it!
Also thanks for the multiple shout-outs on https://dev.to/spike – much appreciated!

**Pull request closed without merging**
