### PR TITLE
Improve environment variables support

### PR DESCRIPTION
**Pull request by toliger**
Makes it possible to define the path of the sqlite file and adds the environment variables "USE_PAYMENTS" and "REGISTRATION_OPEN"

### CODE REVIEW

**Comment by cuu508** [comment]
For `DB_PATH`, maybe use it as-is, without appending "hc.sqlite". In case somebody wants to use a filename other than "hc.sqlite".

For the description, could borrow this from Django docs: "Full path to the sqlite database file. When specifying the path, always use forward slashes, even on Windows."

**Comment by toliger** [comment]
Thank you,

I took in your peace of advice, I renamed `DB_PATH` to `DATA_PATH`.

I changed the description in order to create a more generic folder.

**Comment by cuu508** [comment]
I'd prefer to use something like

    'NAME': os.getenv("DB_NAME", BASE_DIR + "/hc.sqlite")

The DB_NAME variable would need to contain the absolute path including the filename. If DB_NAME is not set then it would default to "hc.sqlite" in project's directory.

I would name it DB_NAME to follow the existing naming convention: DB_HOST, DB_PORT, DB_USER etc.

**Comment by toliger** [comment]
Thank you, it's done.

**Comment by cuu508** [comment]
Thanks!

**Pull request merged**
