### PR TITLE
For email pings, "ping details" dialog box should default to show html if exists, otherwise to plain text.

### PR DESCRIPTION
**Pull request by seidnerj**
I believe the title says it all.

### CODE REVIEW

**Comment by seidnerj** [comment]
Seems like this is failing due to network issues at github when trying to download dependencies...

**Comment by seidnerj** [comment]
@cuu508, please re-run the checks later, I suspect this was a transient issue and the checks should succeed. Thanks!

**Comment by cuu508** [comment]
Thanks for the PR, @seidnerj !

**Comment by seidnerj** [comment]
My pleasure!

**Pull request merged**
